name: geoalert
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
