// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ODNtYioM1-XEmK9EVf-aR1mzgK80024',
    appId: '1:505509737775:web:24a830da05a522a9235dda',
    messagingSenderId: '505509737775',
    projectId: 'ms-notification-4d4f7',
    authDomain: 'ms-notification-4d4f7.firebaseapp.com',
    storageBucket: 'ms-notification-4d4f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWcxIWaAwE3JEVO7tljxEh1ZtBOlk0YjA',
    appId: '1:505509737775:android:4e7645962d268b59235dda',
    messagingSenderId: '505509737775',
    projectId: 'ms-notification-4d4f7',
    storageBucket: 'ms-notification-4d4f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaXEggdv9Y1DSLFghbdZ9fuNkggpiPEUk',
    appId: '1:505509737775:ios:4451bf57fd87dbd3235dda',
    messagingSenderId: '505509737775',
    projectId: 'ms-notification-4d4f7',
    storageBucket: 'ms-notification-4d4f7.firebasestorage.app',
    iosBundleId: 'com.example.geoalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaXEggdv9Y1DSLFghbdZ9fuNkggpiPEUk',
    appId: '1:505509737775:ios:4451bf57fd87dbd3235dda',
    messagingSenderId: '505509737775',
    projectId: 'ms-notification-4d4f7',
    storageBucket: 'ms-notification-4d4f7.firebasestorage.app',
    iosBundleId: 'com.example.geoalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ODNtYioM1-XEmK9EVf-aR1mzgK80024',
    appId: '1:505509737775:web:481503651571abe3235dda',
    messagingSenderId: '505509737775',
    projectId: 'ms-notification-4d4f7',
    authDomain: 'ms-notification-4d4f7.firebaseapp.com',
    storageBucket: 'ms-notification-4d4f7.firebasestorage.app',
  );
}
